set-window-option -g mouse on
set-window-option -g window-status-current-style bright

set-option default-terminal "screen-256color"
set-option -g status-fg colour227
set-option -g status-bg colour233
set-option -g status-position top
set-option -g status-left-length 90
set-option -g status-left '#[bg=colour232]#H:#{pane_current_path}'
set-option -g status-right-length 90
set-option -g status-right '#[bg=colour234]%Y/%m/%d(%a) %H:%M'
set-option -g status-interval 1
set-option -g status-justify centre
set-window-option -g window-status-current-format '[#I-#P:#W]'

# keybind
unbind-key C-b
set-option -g prefix C-t
bind-key C-t send-prefix
bind-key | split-window -hc "#{pane_current_path}"
bind-key - split-window -vc "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection

if-shell "[ `uname -s` = Darwin ]" "\
  bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel pbcopy;
  bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel pbcopy;
  "
